# Generated by Django 4.1.3 on 2022-12-08 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/masters', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'svg'])], verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/salons', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'svg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/services', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'svg'])], verbose_name='Изображение'),
        ),
    ]
