# Generated by Django 4.1.3 on 2023-05-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField(verbose_name='Слот')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='beauty_shop.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'временной слот',
                'verbose_name_plural': 'временные слоты',
            },
        ),
    ]
