# Generated by Django 4.1.3 on 2023-05-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0002_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time_slot',
            new_name='time_slot_at',
        ),
    ]
