# Generated by Django 4.1.3 on 2023-05-29 19:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0003_rename_time_slot_timeslot_time_slot_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='message',
        ),
        migrations.AddField(
            model_name='note',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
    ]
