# Generated by Django 4.1.3 on 2022-12-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0003_alter_client_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='assessment',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='5'),
        ),
    ]
