# Generated by Django 4.1.3 on 2023-05-29 20:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0004_remove_note_message_note_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон'),
        ),
    ]
