# Generated by Django 4.1.3 on 2022-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0004_remove_feedback_subject_alter_feedback_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assessment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='5', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
