# Generated by Django 4.1.3 on 2022-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0005_remove_feedback_assessment_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
