# Generated by Django 4.1.3 on 2023-05-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0005_alter_client_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='note',
            name='payment',
        ),
        migrations.AddField(
            model_name='note',
            name='completed_status',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AddField(
            model_name='note',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
