# Generated by Django 4.1.3 on 2022-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_shop', '0006_note_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
    ]
